theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: test
author: Hz
description: >- 
  关于编程技术的一些浅见。
#baseurl: ""
#url: "https://Zheng7426.github.io"
github_username: Zheng7426
title-logo: /assets/images/title-logo.png