theme: minima
#remote_theme: jekyll/minima

minima:
  skin: auto
  # social_links: 
  #   - { platform: github,  user_url: "https://github.com/Zheng7426" }
    # date_format: "%b %-d, %Y"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-remote-theme

title: 驰歇戏
author: A Hobbit.
  # name: A Hobbit.
  # email: ""
description: >- 
  'I will take the Ring,' he said, 'though I do not know the way.'
#baseurl: ""
#url: "https://Zheng7426.github.io"
github_username: Zheng7426
# title-logo: /assets/images/title-logo.png

collections:
  categories:
    output: true
  # authors:
  #   output: true

# kramdown:
#   syntax_highlighter_opts:
#     disable : true

defaults:
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
    values: 
      layout: "default"